124 show status with problem title and
joonas-yoon/boj-extended pull request #125
Opened 2022-10-17 01:11 UTC by VertexToEdge

**연결된 이슈**
#124 

**내용**
백준 '제출 현황' 페이지의 문제 이름과 번호를 함께 보여주는 기능.
    - 문제 이름 표시 설정(문제 제목표시 or 번호 표시)를 라디오 버튼에서 체크박스로 변경

2022-10-17 01:48 UTC, joonas-yoon requested changes
작업을 잘 해주셨네요 감사합니다 ㅎㅎ 몇 가지 질문이랑 코멘트가 있는데 확인 부탁드립니다 :>

혹시 `dist/` 아래 파일은 직접 추가하신 건가요? gitignore 파일에 추가했는데 스테이지에 왜 같이 올라갔는 지 모르겠네요 :/

https://github.com/joonas-yoon/boj-extended/blob/1dbf878d177c57fccf4296a975c40659ab116d2a/.gitignore#L2

아래 파일들 모두 관련 없는 변경으로 PR에 추가된 것 같습니다.

- `.DS_Store`
- `package-lock.json`
- `dist/`
- `docs/images/screenshot-user.png`

2022-10-17 01:48 UTC, joonas-yoon commented on js/features/status/all.js
> +function _createCheckForm(form, callback) {
사소하지만, 이름은 checkbox 가 어떨까요?

그리고 지금보니까 앞의 `_` 은 큰 의미가 없을 것 같아서 이번 기회에 지워져도 되겠네요 ㅎㅎ

```suggestion
function createCheckboxForm(form, callback) {
```

2022-10-17 01:48 UTC, joonas-yoon commented on js/features/status/all.js
> +    Config.load(Constants.CONFIG_SHOW_STATUS_TITLE, (showTitle) => {
체크박스라면, 설정을 동시에 불러올 필요는 없을 것 같아요.

체크박스 form을 먼저 만든 후에, checked 처리를 하는 건 어때요?

2022-10-17 01:48 UTC, joonas-yoon commented on js/features/status/all.js
> +        showPid,
확장 프로그램 최초 실행시에는 설정 값이 없어서 `undefined` 가 반환됩니다.

`!!showPid` 나 `Boolean(showPid)` 로 감싸서 bool 타입으로 변환 부탁드립니다 :)

2022-10-17 01:48 UTC, joonas-yoon commented on js/features/status/all.js
>        }
문제 번호와 제목 모두 표시하지 않는 경우에는, 아무것도 보여주지 않는 게 의도하신 부분인가요?

의도에 따라서 표시 방법을 바꿀 수 있겠다는 생각이 들어서요.

2022-10-17 01:48 UTC, joonas-yoon commented on options/option.js
> +    oStatusTitle.checked = !(show === false); // default as true
다른 상수를 사용하셨네요 ㅎㅎ 아래를 의도하신 게 맞죠?

그리고 사이트에서 문제 제목을 보여주는 게 기본값은 아니기 때문에, 문제 번호를 보여주는 걸 기본 값으로 하는 게 맞아보입니다 :)

```suggestion
  Config.load(Constants.CONFIG_SHOW_STATUS_PID, (isChecked) => {
    oStatusPid.checked = !(isChecked === false);
  });
  Config.load(Constants.CONFIG_SHOW_STATUS_TITLE, (isChecked) => {
    oStatusTitle.checked = Boolean(isChecked);
```

2022-10-17 01:48 UTC, joonas-yoon commented on js/constants.js
> +  CONFIG_SHOW_STATUS_TITLE: 'show-status-title',
`title`이 모호할 수 있어서, problem title을 의미하는 `ptitle`로 변경 부탁드립니다 :)

2022-10-17 05:38 UTC, VertexToEdge commented on js/features/status/all.js
> +function _createCheckForm(form, callback) {
done in [bf1f1c6](https://github.com/joonas-yoon/boj-extended/pull/125/commits/bf1f1c61d1b29ab6f06c782027822043de7d4ef9)

2022-10-17 05:38 UTC, VertexToEdge commented on js/features/status/all.js
> +    Config.load(Constants.CONFIG_SHOW_STATUS_TITLE, (showTitle) => {
done in [bf1f1c6](https://github.com/joonas-yoon/boj-extended/pull/125/commits/bf1f1c61d1b29ab6f06c782027822043de7d4ef9)

2022-10-17 05:40 UTC, VertexToEdge commented on js/features/status/all.js
> +        showPid,
done in [bf1f1c6](https://github.com/joonas-yoon/boj-extended/pull/125/commits/bf1f1c61d1b29ab6f06c782027822043de7d4ef9)

2022-10-17 05:45 UTC, VertexToEdge commented on js/features/status/all.js
>        }
네 문제 번호와 제목을 체크박스로 바꾸었기 때문에, 최소한 둘 중 하나는 체크되어 있도록 제한하면 어색하게 느낄거라고 생각했습니다.

2022-10-17 05:46 UTC, VertexToEdge commented on options/option.js
> +    oStatusTitle.checked = !(show === false); // default as true
done in b6aad92

2022-10-17 05:46 UTC, VertexToEdge commented on js/constants.js
> +  CONFIG_SHOW_STATUS_TITLE: 'show-status-title',
done in [15b62d1](https://github.com/joonas-yoon/boj-extended/pull/125/commits/15b62d161a0648edcf7c3477b26ba6655a8c344e)

2022-10-17 05:52 UTC, VertexToEdge commented on js/features/status/all.js
>        }
혹시 다른 의견이 있으시다면 추가적으로 리뷰 남겨주시길 바랍니다..

2022-10-17 06:00 UTC, joonas-yoon commented on js/features/status/all.js
>        }
네, 이대로 두는 게 맞아보이네요 ^^ 👍

2022-10-17 06:31 UTC, joonas-yoon commented
네, dist 관련은 어차피 dev 브랜치에서는 영향이 없을 거라 상관 없을 것 같네요 ㅎㅎ 잘 작업해주셨습니다.

그리고 작성해주신 PR은 squash해서 합칠 예정이라 브랜치 히스토리는 깔끔하게 남을거에요 :)

gitignore은 커밋에 코멘트를 남기긴 했는데, `*.err` 가 있는데 `lint.err` 가 또 필요한가요?

2022-10-17 06:41 UTC, VertexToEdge commented
아 이미 *.err가 있었군요. lint.err는 다시 없앴고 lint도 적용하였습니다. 자세한 리뷰 감사합니다.

2022-10-17 06:44 UTC, joonas-yoon commented
감사합니다 😄 

`dist`, `package-lock.json` 등의 파일에서 커밋이 꼬인건, 제가 저녁에 여기 PR 브랜치에 직접 작업하도록 하겠습니다 ^^

2022-10-17 06:45 UTC, VertexToEdge commented
아하 이런.. 감사합니다

2022-10-18 10:43 UTC, joonas-yoon approved these changes

2022-10-18 10:43 UTC, merged

2022-10-18 10:57 UTC, joonas-yoon commented
[커밋을 수정](https://github.com/joonas-yoon/boj-extended/commit/fff7ccb694cb94b5a8c72166d7b9acd11e7463e5) 했습니다 :)

PR 감사합니다 ^^