Feature/compile
joonas-yoon/boj-extended pull request #145
Opened 2023-03-09 14:11 UTC by smartwe

**연결된 이슈**

**내용**

**스크린샷 (선택)**

2023-03-09 14:54 UTC, smartwe commented
@joonas-yoon 확인 부탁드립니다 :)

2023-03-09 15:13 UTC, smartwe commented
`.code.tio.cpp:2:1: error: stray ‘\342’ in program
 ​
 ^
.code.tio.cpp:2:2: error: stray ‘\200’ in program
 ​
  ^
.code.tio.cpp:2:3: error: stray ‘\213’ in program
 ​
   ^
.code.tio.cpp:4:1: error: stray ‘\342’ in program
 ​
 ^
.code.tio.cpp:4:2: error: stray ‘\200’ in program
 ​
  ^
.code.tio.cpp:4:3: error: stray ‘\213’ in program
 ​
   ^` 사이트에서 작성하면 이런 에러가 뜨는군요 처리해줘야겠네요

2023-03-09 15:18 UTC, smartwe commented
> `.code.tio.cpp:2:1: error: stray ‘\342’ in program ​ ^ .code.tio.cpp:2:2: error: stray ‘\200’ in program ​ ^ .code.tio.cpp:2:3: error: stray ‘\213’ in program ​ ^ .code.tio.cpp:4:1: error: stray ‘\342’ in program ​ ^ .code.tio.cpp:4:2: error: stray ‘\200’ in program ​ ^ .code.tio.cpp:4:3: error: stray ‘\213’ in program ​ ^` 사이트에서 작성하면 이런 에러가 뜨는군요 처리해줘야겠네요

-> 인코딩을 변경해주는 방식으로 변경하겠습니다.

2023-03-10 04:24 UTC, joonas-yoon requested changes
`dist/` 이하의 변경 사항들은 모두 제거해주세요. 해당 디렉토리는 빌드 확인을 위한 임시 디렉토리이고 실제로 사용되지는 않습니다.

2023-03-10 04:24 UTC, joonas-yoon commented on src/.babelrc
> +    }]],
이건 어떤 설정인가요? 어떤 이유에서 필요한 부분인 지 설명해주실 수 있을까요?

그리고 24번 라인의 indent가 맞지 않습니다.

2023-03-10 04:24 UTC, joonas-yoon commented on src/js/features/compile.js
> +    await button.addEventListener('click', (evt) => {
```suggestion
    button.addEventListener('click', async (evt) => {
```

이렇게만 수정하시면 됩니다.

`await button...` 은 의도하신 대로 동작하지 않을거에요. 이벤트를 등록하는 것을 await 하는 것이지, 등록된 함수를 await 하지 않습니다.

2023-03-10 04:24 UTC, joonas-yoon commented on src/js/features/compile.js
> +(async function extendCompile() {
`async` 는 불필요합니다.

2023-03-10 04:24 UTC, joonas-yoon commented on src/js/features/compile.js
> +  async function createCompileButton() {
`async` 는 불필요합니다.

2023-03-10 04:24 UTC, joonas-yoon commented on src/js/features/compile.js
> +      buttonClick(input, sourceCodeText);
```suggestion
      await buttonClick(input, sourceCodeText);
```

2023-03-10 04:24 UTC, joonas-yoon commented on src/js/features/compile.js
> +    const lang_json = {
`camelcase` 를 사용하고 있습니다.

2023-03-10 04:24 UTC, joonas-yoon commented on src/js/features/compile.js
> +    );
전부터 궁금했는데 이 유니코드는 왜 필요한건가요? 의미를 알 수 있는 주석이나 변수명이 필요해보입니다.


```suggestion
    // eslint-disable-next-line no-control-regex
    const unexpectedUnicodes = /[\u000d\u0020\u0085\u1680\u2000-\u200a\u2029\u202f\u205f\u3000]+/g;
    code = code.replace(unexpectedUnicodes, ' ');
```

2023-03-10 04:24 UTC, joonas-yoon commented on src/js/features/compile.js
> +    return result;
await 를 사용한다면 아래가 더 올바른 사용으로 보입니다. 더 상위 scope에 있는 `result` 에 대입할 필요가 없습니다.

```suggestion
    return await TIO.run(code, input, lang);
```

2023-03-10 04:28 UTC, smartwe commented on src/js/features/compile.js
> +    );
아니면 코드 작성시 들어가는 불필요한 공백들이 코드에 들어가게 되기 때문에 꼭 필요합니다.

2023-03-10 04:31 UTC, joonas-yoon commented on src/js/features/compile.js
> +    );
그렇군요 그럼 `unexpectedUnicodes` 정도로 이름 지으면 충분하겠네요 :)

2023-03-10 06:27 UTC, smartwe commented
> `dist/` 이하의 변경 사항들은 모두 제거해주세요. 해당 디렉토리는 빌드 확인을 위한 임시 디렉토리이고 실제로 사용되지는 않습니다.

넵

2023-03-10 14:09 UTC, smartwe commented on src/js/features/compile.js
> +(async function extendCompile() {
확인해보니 `const compileButton = await createCompileButton();`이 부분에서 await문이 필요하기에 async를 사용해야할 것 같습니다.

2023-04-08 06:47 UTC, joonas-yoon commented
`dist/` 아래 파일 변경이 계속 살아있네요 음.. 커밋하실 때 어떤 방법으로 하신건가요? `dist/` 아래 파일은 추적되지 않도록 `gitignore`에 추가를 했는데 이해가 잘 안되네요.

명령어나 툴에서 사용하신 방법이 기억나실까요?

2023-04-08 06:51 UTC, joonas-yoon commented
커밋 변경 권한이 없어서.. 우선 제 PR로 합치고 디테일한 부분은 직접 손으로 작업해보겠습니다. 감사합니다.

2023-04-08 06:51 UTC, merged

2023-04-08 07:34 UTC, joonas-yoon reviewed
@smartwe 코멘트 남겼습니다.

2023-04-08 07:34 UTC, joonas-yoon commented on src/js/features/compile.js
> +    return await TIO.run(code, input, lang);
여기서 파라미터 3개 의미랑 리턴 결과값이 뭔가요?

파라미터는 아래처럼 예상하고 있는데, input은 감을 못 잡겠네요. `12 3` 이라고 적으신 것만으로는 예상할 수가 없네요.

- `code`: 컴파일하려는 코드
- `input`: ???
- `lang`: 컴파일하려는 언어

결과값은 배열인 것 같은데, 각각 무엇을 의미하는지 모르겠습니다.

2023-04-08 07:47 UTC, joonas-yoon commented on src/js/features/compile.js
> +    return await TIO.run(code, input, lang);
찾았습니다. https://github.com/AviFS/tio-api

```javascript
async TIO.run(code, input, lang) -> Promise([stdout, stderr+timing, ?])
```

2023-04-08 08:28 UTC, smartwe commented on src/js/features/compile.js
> +    return await TIO.run(code, input, lang);
아 제가 요즘 좀 바빠서 못 봤네요 ㅎㅎ 찾으신건가요?

2023-04-08 09:12 UTC, joonas-yoon commented on src/js/features/compile.js
> +    return await TIO.run(code, input, lang);
네, 이 스레드에 적은 내용은 해결되었습니다.